name: flask dev

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: show environment
        run: |
          echo Hello There
          pwd
          ls -la
          pip install pylint
      -
        name: run pylint
        run: |
          pylint .