name: flask dev

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: show environment
        run: |
          echo Hello There
          pwd
          ls -la
      -
        name: checkout
        uses: actions/checkout@v5
      #-
      #  name: run pylint
      #  run: |
      #    ls -la
      #    pip install flask
      #    pylint .
      -
        name: Super-linter
        uses: super-linter/super-linter@v8.3.2 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.MY_REPO_TOKEN }}