name: flask dev

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: show environment
        run: |
          echo Hello There
          pwd
          ls -la
          pip install pylint
      -
        name: checkout
        uses: actions/checkout@v5
      -
        name: run pylint
        run: |
          pip install -r requirements.txt
          ls -la
          pylint .