name: flask dev

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: show environment
        run: |
          echo Hello There
          pwd
          ls -la
          docker --version
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        run: |
          echo "Trustn0" | docker login --username mkenjis --password-stdin
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mkenjis/flask-test1:latest
      -
        name: Run container
        run: |
          echo docker container run -d -p 5000:5000 mkenjis/flask-test1:latest   