name: flask dev

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: show environment
        run: |
          echo Hello There
          pwd
          ls -la
          pip install pylint
      -
        name: checkout
        uses: actions/checkout@v5
      #-
      #  name: run pylint
      #  run: |
      #    ls -la
      #    pip install flask
      #    pylint .
      -
        name: lint code base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false